---
- name: Deploy mashinka on RPI
  hosts: raspberry
  vars:
    repo: "https://github.com/Nickolaim/mashinka.git"
    mashinka_dir: "{{ catkin_src_dir }}/mashinka"

  tasks:
    - include_vars: file=common_vars.yml
    - file: path="{{ catkin_ws_dir }}" state=directory
    - file: path="{{ catkin_src_dir }}" state=directory
    - file: path="{{ mashinka_dir }}" state=directory
    - apt: name=git state=present
      become: yes
    - git: repo="{{ repo }}" dest="{{ mashinka_dir }}"
    - shell: source {{ ros_setup }} && cd {{ catkin_ws_dir }} && catkin_make
      args:
        executable: /bin/bash

