---
- name: Deploy mashinka on RPI
  hosts: raspberry
  vars:
    catkin_ws_dir: "~/catkin_ws"
    catkin_src_dir: "{{ catkin_ws_dir }}/src"
    repo: "https://github.com/Nickolaim/mashinka.git"
    ros_distro: "indigo"
    ros_setup: "/opt/ros/{{ ros_distro }}/setup.bash"

  tasks:
    - file: path="{{ catkin_ws_dir }}" state=directory
    - file: path="{{ catkin_src_dir }}" state=directory
    - apt: name=git state=present
      become: yes
    - git: repo="{{ repo }}" dest="{{ catkin_src_dir }}"
    - shell: source {{ ros_setup }} && cd {{ catkin_ws_dir }} && catkin_make
      args:
        executable: /bin/bash

